version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "async-lambda-practice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l1851p6w0w0d"
s3_prefix = "async-lambda-practice"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
